### ISSUE TITLE
[feat]Unable to change auth token while using the helm chart.

### ISSUE THREAD

**Issue by Annavar-satish** [kore3lab/dashboard#145]
- [feature] request for enabling the auth changes from values file in helm chart [kore-board].

**Comment by itnpeople** [comment]
Do you mean the Helm chart will reflect the authentication settings like in the user guide below?

https://github.com/kore3lab/dashboard/blob/master/docs/user/config-sign-in.md

**Comment by Annavar-satish** [comment]
yes

**Comment by Annavar-satish** [comment]
closing the issue as PR merged. #146

**Comment by Annavar-satish** [comment]
@itnpeople can you please release the chart version 0.5.6.

**Comment by itnpeople** [comment]
@Annavar-satish  

https://github.com/kore3lab/dashboard/releases/tag/v0.5.6
`docker pull ghcr.io/kore3lab/kore-board.{modules_name}:v0.5.6`

**Comment by Annavar-satish** [comment]
thanks @itnpeople but I wanted to use the helm chart version 0.5.6 as it was not available in the `index.yaml`.
can you please update the `index.yaml` using below command 
`helm repo index scripts/install/kubernetes --merge scripts/install/kubernetes/index.yaml`
