### ISSUE TITLE
Metrics Chart 개선

### ISSUE THREAD

**Issue by seyunpark** [kore3lab/dashboard#50]
- [x] memory 그래프 표시에 K,M,G 등 단위 기입 또는 천단위 구분자 필요.
- [x] cpu, memory 차트에 request, limit 표시
- [x] ~~metric 값과 request, limit 값의 차이가 클 경우 중간 생략(보류)~~

**Comment by itnpeople** [comment]
* 전체 차트에서 단위 노출
